apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: helloworld
spec:
  commonName: it.actually.works
  dnsNames:
  - it.actually.works
  issuerRef:
    kind: Issuer
    # name: letsencrypt
    name: letsencrypt-staging
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys
status: {}
